### ISSUE TITLE
Phishing Warning Banner Issue - Persistent banner upon page change distorts page layout and blocks actions

### ISSUE THREAD

**Issue by laurent387** [SaTT-Wallet/Frontend#313]
### Description:

Hello,

I'm encountering an issue with the "Phishing Warning" banner. Despite closing it, the banner reappears each time I navigate to a different page. The persistent banner is causing distortion to certain pages' layout and is obstructing some functionalities, rendering them unusable.
![image](https://github.com/SaTT-Wallet/Frontend/assets/75429104/4d9c023b-c253-4c94-8beb-0571529f0a64)

### To reproduce the issue:
1. Log into the platform.
2. Notice the "Phishing Warning" banner at the top.
3. Close the banner by clicking the 'X' or 'Close' button.
4. Navigate to another page within the platform.

### Expected outcome:
Once closed, the "Phishing Warning" banner should remain closed throughout the session, across all pages.

### Actual outcome:
The "Phishing Warning" banner reappears every time a new page is accessed, distorting the page's layout and blocking some actions.

This issue is becoming a hindrance for users who need to perform certain actions on the affected pages. Could you please investigate this problem and propose a fix? Thank you for your attention to this matter.

Best regards,

Laurent

**Comment by kachourihassen** [comment]
This issue was fixed after the update in the token info page.
