### ISSUE TITLE
incorrect display/current balance/old wallet

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#487]
- [ ] **Preconditions:**
Account SaTT with wallets V1 and V2.

- [ ] **Scenario:**
Sign in.
Access the wallet page.

- [ ] **Result obtained:**
Display of the old wallet.
The current balance of the new wallet is displayed instead of the old wallet.

[current balance.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/0d21244c-4913-47bd-9715-5838685e1906)

**Comment by waelhanfi04** [comment]
@Marwa7894  La mise à jour du backend n'a pas été effectuée hier, tu peux le tester maintenant.

**Comment by Marwa7894** [comment]
@waelhanfi04 le problème est toujours d'actualité 

[balance.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/239d2bfb-217c-440f-b650-91ea2724961e)

**Comment by Marwa7894** [comment]
There is still an issue with the balance display between the new and old wallet

[3.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/197ba72f-e8d0-4f32-bd97-2db35bfc55e7)
