### ISSUE TITLE
Page Campaign Creation/Token List

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#510]
**Scenario:**

    Access the AdPool page.
    Attempt to create a campaign.
    Open the dropdown list of tokens.
    Search for a token that does not exist in the list of tokens.

**Expected Results:**

    1) A link appears: "Add a personalized token."
    2) By manually adding a new token, each token should have its own logo.

**Actual Results:**

    1) There is a spelling mistake regarding the word "personnaliszed" -> "personalized."

![Sans titre3](https://github.com/SaTT-Wallet/Frontend/assets/135624031/808a3869-5c2e-433c-a6a4-d24bd417351d)

    2) The newly added tokens have the same logo.

[logo token.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/db0f08a8-1770-49ed-99c2-7e4401ca3809)

    3) The dimensions of the fields for "TOKEN'S CONTRACT ADDRESS," "TOKEN'S SYMBOL," and "DECIMALS" do not match the Figma 
        design

![Sans titre5](https://github.com/SaTT-Wallet/Frontend/assets/135624031/f1573aae-ee62-4fd0-9a41-00dbe2535e04)

**Comment by Marwa7894** [comment]
- the word "personalized" has a single "n"

![Capture d’écran du 2023-09-13 15-22-47](https://github.com/SaTT-Wallet/Frontend/assets/135624031/ebd9ddb4-bf1a-41b4-8140-6233de0669df)

- added tokens do not display their own logo

[Capture vidéo du 13-09-2023 15:52:18.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/8ca0ec3f-2f90-4866-bea2-44a3eb56383a)

**Comment by waelhanfi04** [comment]
I will fix the word 'personalized' in the next edit, but 'added tokens do not display their own logo' doesn't work on the testnet; it only works on prod since it's fetched from the CoinMarketCap API.

**Comment by Marwa7894** [comment]
@waelhanfi04 
Even on the prod, when adding a new token, its logo doesn't appear

[symbole.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/0a249b3f-1879-406b-86da-b023cacc52fa)
