### ISSUE TITLE
Time/Campaign Availability

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#580]
**Scenario:**
- Create a campaign.
- Check the activation popup.

**Expected Result:**

- The popup should display the activation time of the campaign.

**Actual Result:**

- After creating the campaign, the popup does not show the correct availability time for the campaign. 
![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/bce657e7-9004-4fae-b8b5-abc783f617d5)

- The activation time has already passed, but the campaign remains in the "pending" state.
![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/ce142060-0531-4d29-960b-0c8962cb780d)

**Comment by waelhanfi04** [comment]
I tested and checked the condition, and I found that everything is correct. I launched the campaign, and after one hour, the status changed from 'pending' to 'manage my pool

**Comment by Marwa7894** [comment]
I have tested this case again, and the issue is still ongoing; the campaign becomes active 15 minutes after the initially scheduled launch time

**Comment by waelhanfi04** [comment]
@Marwa7894  I checked the code and found the following code:

if (
  start.setDate(start.getDate() + 15) >=
  today.setHours(0, 0, 0, 0)
) {
  return true;
} else {
  return false;
}

Please check if the scenario is intended to start the campaign after 15 minutes or not.

**Comment by Marwa7894** [comment]
@waelhanfi04 According to the test case, the campaign should be available when the time specified at launch is reached
