### ISSUE TITLE
Token "SaTT" - Default Display in the Token List of Adpool-BEP20

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#583]
**Scenario:**

- Attempt to create a campaign.

-  Select the BEP20 network.

- Open the "select token" popup by clicking on the token dropdown list.

**Expected Result:**

- Change the "Doge" token to the default "SaTT" token.

![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/139344a5-331f-441c-a2e7-1ab5fa644720)

**Comment by waelhanfi04** [comment]
This issue is fixed.
<img width="736" alt="image" src="https://github.com/SaTT-Wallet/Frontend/assets/79511539/fcb31487-ab93-48f2-a6fb-3a3afc3a117f">
