### ISSUE TITLE
Countdown Display Between Two Harvests

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#611]
**Scenario:**
-Participate in a campaign.
-Validate this link.
-Perform the harvest with this link.
-Attempt to perform the second harvest.

**Expected Result:**
-A countdown should appear, and it should not be possible to perform a new harvest with the same link until 24 hours have passed since the previous harvest, with the countdown displayed.

**Actual Result:**
-The countdown does not appear, and access to the harvest page is possible.

[2nd harvest.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/985995f1-e3bd-4a0c-9dda-efc586940650)

**Comment by Marwa7894** [comment]
- Right after validation, the countdown timer doesn't appear next to the participation link

![Sans titre7](https://github.com/SaTT-Wallet/Frontend/assets/135624031/4b331916-81d4-4703-9229-e8afa26cb70a)

- For the second harvest, the countdown timer only appears when you access the "harvest" modal and attempt to claim your earnings. Upon returning to the post-farming page and refreshing it, the countdown timer appears, but it displays 25 hours instead of 24 hours, with negative symbols

[harvest linkedin 2.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/56368cbe-98bd-4b13-b2d4-a8d0abb1d5ea)

**Comment by waelhanfi04** [comment]
In 'farm-post-card.component.ts':
   - Made minor changes to calculate 'timeUntilAccepted' based on the provided timestamps.
   
@Marwa7894  please check now

**Comment by Marwa7894** [comment]
@waelhanfi04 The countdown timer is increasing instead of decreasing

![Sans titre9](https://github.com/SaTT-Wallet/Frontend/assets/135624031/7c0a1dbd-8f38-40af-99cf-9694323d35e2)
![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/3aaa5eb2-11a8-4037-9c99-45df097bae36)

**Comment by waelhanfi04** [comment]
@Marwa7894  the bug has been fixed

**Comment by Marwa7894** [comment]
@waelhanfi04 Yes, the issue has been fixed, and I closed it.
