### ISSUE TITLE
welcome page problems 

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#625]
- At the "welcome page," the blog articles are not displaying. This issue has been identified on both the prod and testnet

![Sans titre3](https://github.com/SaTT-Wallet/Frontend/assets/135624031/db886cc3-663d-4043-b1f1-1e80ff9f8df0)

- Table of Contents for Welcome Page, display issue on testnet

![Sans titre4](https://github.com/SaTT-Wallet/Frontend/assets/135624031/e4ad4f5b-8b76-48bc-acad-6a2c4663a90d)

**Comment by waelhanfi04** [comment]
@Marwa7894  the bug has been fixed is related to cors policy

**Comment by Marwa7894** [comment]
The issue has been resolved in the Prod, but the problem with the summary display persists on the testnet.

![image](https://github.com/SaTT-Wallet/Frontend/assets/135624031/9750cead-c78b-4c2a-9bf4-3c3104cda2a6)

**Comment by Marwa7894** [comment]
fixed

**Comment by Marwa7894** [comment]
Fixed
