### ISSUE TITLE
Buy page/blue banner/icon display issue

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#629]
**- Scenario:**
Access the wallet page.
Click on the "buy" button for the "MAKER" token, for example.

**- Result obtained:**
Redirected to the purchase page, but a blue banner appears.
For some tokens, the icon does not appear on the purchase page.

[page buy.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/6d47fe7d-ca5b-4ade-abef-d6f2a7906835)

**Comment by waelhanfi04** [comment]
@Marwa7894  I didn't find the issue

[SaTT - Smart advertising Transaction Token.webm](https://github.com/SaTT-Wallet/Frontend/assets/79511539/92240eee-3aa9-42ed-ae2c-fcd5a0ffeaed)

**Comment by Marwa7894** [comment]
@waelhanfi04 The issue persists with the Firefox browser

[blue banner.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/6c40f9a3-d147-4ac6-93a2-14806727cc92)
