### ISSUE TITLE
Retrieve Budget from Feed

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#630]
**Preconditions:**
- Have a campaign available to retrieve earnings.

**Scenario:**
- Access the "Feed" page.
- Attempt to retrieve earnings from a notification.
- Click on the "Retrieve Budget" button.

**Expected Result:**
- A pop-up opens to enter the "transaction password."

**Actual Result:**
- Redirected to the campaign page.

[feed retrieve budget.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/e751e0db-f4cb-4597-9267-2d89777c1a53)

**Comment by waelhanfi04** [comment]
@Marwa7894  the bug has been fixed

**Comment by Marwa7894** [comment]
fixed, I closed the issue.
