### ISSUE TITLE
Failure to import tokens by name

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#635]
**Scenario:**
- Access the wallet page.
- Search for a token -> a list of tokens is displayed.
- Attempt to add one by clicking "import this token."

**Expected result:**
- The token is successfully added to the cryptocurrency list.

**Actual result:**
- Token addition failed.

[import token.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/8a5a94ea-d6cc-422d-b6e8-f85dc4c0cce0)
 

**note:** This form should only be displayed when no tokens appear in the search results.

![Sans titre8](https://github.com/SaTT-Wallet/Frontend/assets/135624031/0ac78325-9867-41cb-9b15-b8eeb1ccea78)

**Comment by skanderKha** [comment]
Update : Now the form will no longer appear only if there is no token as a result of the search token
