### ISSUE TITLE
change of direction

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#683]
**Scenario:**
Navigate to the page: "https://satt-token.com/"
Click on the "sign in" button.

**Obtained result:**
Redirected to the "sign in" page.

**Expected result:** 
Redirected to the "welcome page."

[satt.token.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/2fd52607-8bea-4d90-908f-286a0d36565e)

**Comment by skanderKhabou** [comment]
the button now redirect to the right page ! , the link was changed for the two languages
