### ISSUE TITLE
"Apply Now" button / Adpool

### ISSUE THREAD

**Issue by Marwa7894** [SaTT-Wallet/Frontend#716]
**Scenario:**
Accessing the campaign as a participant

->> The "Apply now" button should remain displayed below the cover when scrolling down.

[apply now.webm](https://github.com/SaTT-Wallet/Frontend/assets/135624031/da2d7c8d-a187-4667-9215-f048620b9f37)

**Comment by skanderKha** [comment]
done in branch 716-716
